# Generated by Django 2.2.10 on 2020-04-02 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='authorDetail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.AuthorDetail', verbose_name='外键连接到作者详细信息'),
        ),
    ]
